apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
      #   nodeSelectorTerms:
      #   - matchExpressions:
      #     - key: kubernetes.io/hostname
      #       operator: In
      #       values:
      #       - gke-sace2022-sace-pool-3a2dd1f5-3ntx
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 99
        preference:
          matchExpressions:
          - key: performance
            operator: In
            values:
            - low
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0

