apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: staging
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "1024M"
        cpu: "4"
  nodeSelector:
    performance: low