service:
  type: LoadBalancer
# Set to Recreate if you use persistent volume that cannot be mounted by more than one pods to make sure the pods is destroyed first.
grafana:
  updateStrategy:
    type: Recreate
persistence:
  enabled: true
  storageClass: ""
  accessModes: ReadWriteOnce
  size: 10Gi