apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-training
  labels:
    app: monolith-training
spec:
  replicas: 3
  strategy:
    type: Recreate
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 25%
    #   maxUnavailable: 25%
  selector:
    matchLabels:
      app: monolith-training
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9464"
        prometheus.io/scrape: "false"
      labels:
        app: monolith-training
    spec:
      containers:
      - name: monolith-training
        image: esparta2018/development:tigo-training-app-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "2"
            memory: "2048M"