apiVersion: v1
kind: Service
metadata:
  labels:
    app: monolith-training
  name: monolith-training
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: monolith-training
  type: NodePort