apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # propiedades key; Cada key tiene su valor
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # Archivo de key valor
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true 