apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Se define la variable de ambiente
        - name: PLAYER_INITIAL_LIVES
          valueFrom:
            configMapKeyRef:
              name: game-demo           # nombre del volumen configmap
              key: player_initial_lives # nombre de la llave para extraer su valor
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: ui_properties_file_name
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    # Definiendo los volumenes a utilizar, Luego tu en cada contenedor en que los necesites, los montas
    - name: config
      configMap:
        # Proveer el nombre del configmap creado
        name: game-demo
        # Un arreglo de llaves para crearlos como archivos dentro del contenedor
        items:
        - key: "game.properties"
          path: "game.properties"
        - key: "user-interface.properties"
          path: "user-interface.properties"