apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        # El nombre aca debe concidir con el nombre del volumen
        - name: secret-volume
          mountPath: /etc/secret-volume
  # La data de un secret es expuesta hacia un container en el pod por un volumen
  volumes:
    - name: secret-volume
      secret:
        secretName: credentials-app